### ISSUE TITLE
Add support for Moment coefficient and Lateral coefficient

### ISSUE THREAD

**Issue by SimLend** [alobazombie/kOS-Ferram#1]
There would be nice to have access to the moment coefficient (useful for autopilot conception and stability analysis) and to lateral lift coefficient, usefull for yaw controllers.

Also would it be possible to increase the number of variables inside the "simulation" function in order to take the elevon deflection as a parameter?

**Comment by giuliodondi** [comment]
Hello, sorry for the belated reply.
Perhaps this wasn't clear enough in the readme, but this addon is simply a bridge between Ferram Aerospace and kOS. Everything that could possibly be made available to kOS has to exist in the Ferram API (the files that specifies what features of Ferram are visible ot other modules) and can only be used exactly as defined in the API.

To answer your second request: no, unless one first modifies the Ferram method that is referenced by the API, but that would require digging into the Ferram mod which I don't have time to do right now.
If anyone ever did that, it would propably exist as a standalone modification to Ferram rather than an addition to this plugin anyways.

Regarding your first request: the same applies, as no methods exist in the API which give what you request. The Ferram API, however, provides a couple of methods to get the Vessel Aerodynamic torque, which so far I didn't include.
It gives out a vector indicating the touque direction and magnitude of a vessel at the moment. There is no method to predict the aerodynamic torque given a velocity vector like there is for the aerodynamic force, though.  I'm not strong in aerodynamics so I don't know if the moments can be obtained from this.
